### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by v6** [BlockIo/block_io-java#1]
I know this supports testnet addresses, but would you be willing to provide a document as a quick walkthrough for setting up testnet accounts? 

I think this is one of the chief use-cases of a service like block.io.

**Comment by doersf** [comment]
Hey Nate, there's a Java library that's been in the works but does not yet have Distributed Trust capabilities. You can find it here: https://github.com/langerhans/blockio-java. It will get merged to this repository as soon as it's up to speed with dTrust. However, it should work for regular 2-of-2 MultiSig addresses.

The developer is @langerhans, a core developer for Dogecoin. I'll get him in here to answer your query directly.

**Comment by v6** [comment]
Has anyone done anything on this with Python? or python-ish?

**Comment by doersf** [comment]
Ofcourse, here: https://github.com/BlockIo/block_io-python. Mikko (formerly CTO of Local Bitcoins) used this library to build:

* Liberty Music Store: https://libertymusicstore.net/
* Crypto Core Assets: https://pypi.python.org/pypi/cryptoassets.core

**Comment by v6** [comment]
Awww, sweeeet.

I'm actually at the Bitcoin Job Fair Bithack, right now.

BitGo is here, too.

Do you think you'll be coming?

 : Nathan Basanese
   4086576639

P.S. A lot of companies are going to need pre-funded testnet wallets for
automatic testing, I think.

**Comment by doersf** [comment]
Indeed. Cheers :)

Might stop by, but no plans right now.

Atif Nazir
415-515-9061
